<div class="mt-8">
            <ul
                class="mx-3 md:ml-32">
                <li class="px-3 py-2"><strong> Prof. Xavier Fernando</strong>, Toronto, Metropolitan University, Toronto</li>
                <li class="px-3 py-2"><strong> Prof. Frank Wang</strong>, Ex Head of School of Computing, University of Kent, UK</li>
                <li class="px-3 py-2"><strong> Prof Chuan-Ming Liu</strong>, National Taipei University of Technology, Taipei, Taiwan</li>
                <li class="px-3 py-2"><strong> Prof. Saraju Mohanty</strong>, University of North Texas</li>
                <li class="px-3 py-2"><strong> Prof. Linga Reddy Cenkeramaddi</strong>, University of Agder Grimstad, Norway</li>
                <li class="px-3 py-2"><strong> Prof. James Swart</strong>, Central University of Technology, South Africa</li>
                <li class="px-3 py-2"><strong> Dr. Veepsa Bhatia Lohit</strong>, Southern Methodist University, USA</li>
                <li class="px-3 py-2"><strong> Prof. Aarti Singh</strong>, Carnegie Mellon University, Pittsburgh, Pennsylvania</li>
                <li class="px-3 py-2"><strong> Dr. Prasanalakshmi Balaji</strong>, King Khalid University, Saudi Arabia</li>
                <li class="px-3 py-2"><strong> Prof. Anand Nayyar</strong>, Duy Tan University, Vietnam</li>
                <li class="px-3 py-2"><strong> Dr. S.B.Goyal</strong>, Director, City University, Peatling Jaya, Malaysia</li>
                <li class="px-3 py-2"><strong> Dr. Dilbagh Singh</strong>, New York University, USA</li>
                <li class="px-3 py-2"><strong> Ms. Barkha Pabra</strong>, University of west of Scotland, UK</li>
                <li class="px-3 py-2"><strong> Mr. Miguel Botto-Tobar</strong>, Researcher, Eindhoven University of Technology, Netherlands</li>
                <li class="px-3 py-2"><strong> Prof. Narendra S. Chaudhari</strong>, IIT Indore, India</li>
                <li class="px-3 py-2"><strong> Prof. Ashok De</strong>, DTU, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Lavika Goel</strong>, MNIT, Jaipur, India</li>
                <li class="px-3 py-2"><strong> Dr. Kakali Chaterjee</strong>, NIT, Patna, India</li>
                <li class="px-3 py-2"><strong> Dr. Madhu Sharma</strong>, DIT, Dehradun, India</li>
                <li class="px-3 py-2"><strong> Dr. Vineet Kumar</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Prof. K.P.S. Rana</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Shailendra Kumar</strong>, DTU, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Vijyander Singh</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Prof. A. K. Mahapatra</strong>, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Prof. Poonam Bansal</strong>, IGDTUW, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Robin Singh Bhadoria</strong>, NIT Hamirpur, Himachal Pradesh, India</li>
                <li class="px-3 py-2"><strong> Dr. Rizwan Khan</strong>,  Dean Emerging Technologies, ABES Institute Of Technology(ABESIT), Ghaziabad, India</li>
                <li class="px-3 py-2"><strong> Dr. Rohit Beniwal</strong>, DTU, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Kanchan Sharma</strong>, IGDTUW, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Sanjib Kumar Sahu</strong>, IGDTUW, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Sudhanshu Tyagi</strong>, Thapar University, India</li>
                <li class="px-3 py-2"><strong> Dr. Madhu Sharma</strong>, DIT, Dehradun, India</li>
                <li class="px-3 py-2"><strong> Dr. Naresh Kumar Yadav</strong>, DCRUST, Murthal, India</li>
                <li class="px-3 py-2"><strong> Dr. Ankita Jain</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Deepika</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Pankaj Lathar</strong>, DSEU, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Malaaya Dutta Borah</strong>, NIT, Silchar, India</li>
                <li class="px-3 py-2"><strong> Dr. Amit Chaudhary</strong>, GGSIPU, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Manisha Bharti</strong>, NIT, New Delhi</li>
                <li class="px-3 py-2"><strong> Dr. Rajendra Kumar</strong>, NIT, Kurukshetra, India</li>
                <li class="px-3 py-2"><strong> Dr. Saurabh Bhardwaj</strong>, Thapar University, India</li>
                <li class="px-3 py-2"><strong> Dr. Rajit Nair</strong>, VIT, Bhopal, India</li>
                <li class="px-3 py-2"><strong> Dr. Tarun Rawat</strong>, NSUT, New Delhi, India</li>
                <li class="px-3 py-2"><strong> Dr. Bharti Sharma</strong>, JIT, Dehradun, India</li>
                <li class="px-3 py-2"><strong> Dr. Prachi Chaudhary</strong>, DCRUST, Murthal, India</li>
                <li class="px-3 py-2"><strong> Dr. Deepali Gupta</strong>, Chitkara University, Rajpura, Punjab, India</li>
                <li class="px-3 py-2"><strong> Mr. Rajeev Kumar</strong>, IEEE Member, USA</li>
            </ul>
</div> 