<div class="mt-8">
            <ul
                class="mx-3 md:ml-32">
                <li class="px-3 py-2"><strong>Prof. Prasanalakshmi Balaji</strong>, King Khalid University (Saudi Arabia)</li>
                <li class="px-3 py-2"><strong>Dr. Aakansha Garg</strong>, ABESIT, Ghaziabad (INDIA)</li>
                <li class="px-3 py-2"><strong>Mr. Abhinav Mehta</strong>, Amazon.com Services LLC (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Aijaz Ahmed</strong>, National Institute of Technology Delhi, (INDIA)</li>
                <li class="px-3 py-2"><strong>Mr. Amit Dhiman</strong>, HCL, (U.S)</li>
                <li class="px-3 py-2"><strong>Mr. Ankit Chouhan</strong>, University of Regina, (Canada)</li>
                <li class="px-3 py-2"><strong>Dr. Arvind Goswami</strong>, Delhi Technological University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Arvind Panwar</strong>, Galgotias University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Ashish Kumar</strong>, VIPS-TC, School of Engineering & Technology, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Ashish Kumar</strong>, Bennett University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Ashutosh Gupta</strong>, Delhi Technological University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr Jaspreet Kaur</strong>, JSS,Noida (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Deepak Kumar Sharma</strong>, IGDTUW (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Kaushik Ghosh</strong>, School of Computer Science, UPES. (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Bimlesh Wadhwa</strong>, National University of Singapore (Singapore)</li>
                <li class="px-3 py-2"><strong>Dr. Veepsa Bhatia</strong>, Southern Mellon University (U. S.)</li>
                <li class="px-3 py-2"><strong>Dr. Malaya dutta borah</strong>, NIT Silchar, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Alka Singhla</strong>, Jaypee, Noida (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Monika Arora</strong>, BPIT, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Nisha Agarwal</strong>, Maharaja Agrasen Institute of Technology, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Amandeep Kaur</strong>, GTBIT, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Rachna Jain</strong>, JSS, Noida (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Indu Kashyap</strong>, MRIIRS, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Amita mali</strong>, Dcrust, murthal (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Shweta Singhal</strong>, IGDTUW, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Aakanshi Gupta</strong>, Amity University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Xiochun Cheng</strong>, Swansea University, (U.K.)</li>
                <li class="px-3 py-2"><strong>Dr. Shweta Singh</strong>, Mathworks, Boston (U.S.)</li>
                <li class="px-3 py-2"><strong>Dr. Anju Bhandai</strong>, PIET Samalkha, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Rattandeep Aneja</strong>, CUIET, Chitkara University (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof. Vineet Kumar</strong>, Netaji Subas University of Technology, (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof. Shailendra Kumar</strong>, Delhi Technological University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Arvind Panwar</strong>, Galgotias University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Mr. Amit Dhiman</strong>, HCL Technologies, Texas, (USA)</li>
                <li class="px-3 py-2"><strong>Dr. Ankur Suri</strong>, University of Washington, (USA)</li>
                <li class="px-3 py-2"><strong>Dr. Jagadeesh Kadiyam</strong>, IIT Mandi (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Siddharth Panwar</strong>, IIT Mandi, (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof. Poonam</strong>, Professor, DCRUST, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Jyoti Yadav</strong>, Netaji Subas University of Technology, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Dinesh</strong>, IGDTUW, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Tajindar Singh Arora</strong>, Aligarh Muslim University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Vijay Nath</strong>, BITS, Mesra, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Rajanish Kr. Singh</strong>, IIIT Nagpur, (INDIA)</li>
                <li class="px-3 py-2"><strong>Mr. Atul Bhargava</strong>, ST Microelectronics, (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof Navin Rajpal</strong>, GGSIPU, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr Munish rattan</strong>, GNDEC, Ludhiana, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr Manisha Bharti</strong>, NIT, Delhi, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Nidhi Sindhwani</strong>, Amity University, NOIDA, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Deepa Gupta</strong>, Amity University, NOIDA, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Rohit Anand</strong>, G.B. Pant DSEU, OKHLA, (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof.(Dr.) R. Rama Kishore</strong>, USICT, GGSIPU, (INDIA)</li>
                <li class="px-3 py-2"><strong>Prof.(Dr.) Harish Rohil</strong>, Dept. of CSE, CDLU , SIRSA (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Anu Saini</strong>, G.B. Pant Engg. college, DSEU, Delhi, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Mamta Kumari</strong>, PIET, Panipat, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Uma Nangia</strong>, Delhi Technological University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Poonam Chaudhary</strong>, The NorthCap University, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Daya Pandey</strong>, University of Leads (England)</li>
                <li class="px-3 py-2"><strong>Dr. Chico Camargo</strong>, University of Exeter, (England)</li>
                <li class="px-3 py-2"><strong>Mr. Vineet Aggarwal</strong>, RENXO Technologies, (INDIA)</li>
                <li class="px-3 py-2"><strong>Dr. Prabhaker Mateti</strong>, Wright State University (USA)</li>
                <li class="px-3 py-2"><strong>Prof. Richard Chbeir</strong>, Université de Pau et des Pays de l'Adour (UPPA), Anglet (FRANCE)</li>
                <li class="px-3 py-2"><strong>Prof. Mohamed Hamada</strong>, The University of Aizu, Fukushima (JAPAN)</li>
                <li class="px-3 py-2"><strong>Prof. Xiochun Cheng</strong>, Swansea University (United Kingdom)</li>
                <li class="px-3 py-2"><strong>Prof. Joan Lu</strong>, University of Huddersfield (United Kingdom)</li>
            </ul>
</div>